RANGOS = [
    {
        'name': 'Afiliado',
        'pv_requerido': 13,
        'brazo_pago': 0,
        'brazo_pago_max': 0,
        'comision_binario': 0,
        'pv_mlm_requerido': 0,
        'mlm_max': 0,
        'comision_mlm': 0,
        'mlm_brazo_poder': 0,
    },
    {
        'name': 'Bronce',
        'pv_requerido': 13,
        'brazo_pago': 78,
        'brazo_pago_max': 200,
        'comision_binario': 40,
        'pv_mlm_requerido': 90,
        'mlm_max': 200,
        'comision_mlm': 38,
        'mlm_brazo_poder': 13,
    },
    {
        'name': 'Plata',
        'pv_requerido': 26,
        'brazo_pago': 300,
        'brazo_pago_max': 500,
        'comision_binario': 40,
        'pv_mlm_requerido': 390,
        'mlm_max': 400,
        'comision_mlm': 28,
        'mlm_brazo_poder': 90,
    },
    {
        'name': 'Oro',
        'pv_requerido': 39,
        'brazo_pago': 750,
        'brazo_pago_max': 900,
        'comision_binario': 35,
        'pv_mlm_requerido': 900,
        'mlm_max': 650,
        'comision_mlm': 24,
        'mlm_brazo_poder': 150,
    },
    {
        'name': 'Zafiro',
        'pv_requerido': 39,
        'brazo_pago': 1500,
        'brazo_pago_max': 1800,
        'comision_binario': 25,
        'pv_mlm_requerido': 1800,
        'mlm_max': 950,
        'comision_mlm': 22,
        'mlm_brazo_poder': 300,
    },
    {
        'name': 'Rubi',
        'pv_requerido': 52,
        'brazo_pago': 3000,
        'brazo_pago_max': 3800,
        'comision_binario': 24,
        'pv_mlm_requerido': 3600,
        'mlm_max': 1550,
        'comision_mlm': 20,
        'mlm_brazo_poder': 600,
    },
    {
        'name': 'Diamante',
        'pv_requerido': 70,
        'brazo_pago': 7000,
        'brazo_pago_max': 10000,
        'comision_binario': 20,
        'pv_mlm_requerido': 10000,
        'mlm_max': 2500,
        'comision_mlm': 18,
        'mlm_brazo_poder': 2500,
    }
]
